### PR TITLE
Include Typescript Typings in NPM Package, Add support for id and tags in types

### LINKED ISSUE #48: Including Typescript types in package.json
Hello hello. I believe the types aren't working at the moment since they aren't being included in the final NPM package. We'll need to copy them over to the final package for them to work.

It should be easy for us to do this by including the types in the `files` section of the `package.json`.

### PR DESCRIPTION
**Pull request by ethan-ou**
Resolves #48 and adds additional typings for #44.

I've set the typings for the additional `id` and `tags` keys to be optional. I think doing so supports the notion that `id` and `tags` keys are optional extras, and don't have to be included in the parser output. But let me know about your opinion on this.

Two other changes made:
1. Clarify the difference between TextChoice and NumericalChoice in typings. This should lead to clearer disambiguation between numerical vs multiple choice/short answer questions when using Typescript.
2. Added an extra install section to the Readme.

### CODE REVIEW

**Comment by fuhrmanator** [comment]
Thanks for helping out on this! Do you think you can make some tests to validate the TypeScript types (especially with respect to your TextChoice vs NumericalChoice) if that makes sense? I'm using Mocha for those parser tests, but maybe Jest is easier for what you want to do? The idea is that if we change (break) something in the types, the tests will catch it. It's also a kind of specification of how it is supposed to work.

**Comment by fuhrmanator** [comment]
@ethan-ou Have a look at this blog entry and see if it makes sense to you: https://medium.com/front-end-weekly/testing-typescript-types-1595c641d7c7

**Comment by fuhrmanator** [comment]
@ethan-ou Because I merged #47 (all the id and tag parsing tests pass), it created a small conflict with your package-lock.json

**Comment by ethan-ou** [comment]
Testing Typescript types is a good idea. I'll try to integrate it with the existing tests in mocha and we can validate from there.

I'll also sync up your changes in my pull to avoid the conflict.

**Comment by ethan-ou** [comment]
After some testing I think the `tsd` library might be a good solution for us. Happy to use it, but I'm waiting on a pull request from the library to resolve some internal bugs. For now, I'll set the version of the library to `0.14.0` since the current version `0.15.0+` has issues with some of the core library.

One thing I haven't been able to fix is mocha. I'm currently unable to run the tests on my machine.

**Comment by fuhrmanator** [comment]
I wish `tsd` had some verbose option to see that tests are passing 😕 but I think it is working. 

Thanks for your help! I merged this and there's now a new version of gift-pegjs (0.2.0) on npm. You should be able to work on tag/id support if you so choose in your previewer. For now, I'm not working on supporting that in the web version, but will get around to it on a rainy day :)

**Comment by fuhrmanator** [comment]
Also, I decided not to use a true PEG strategy to parse the tags inside comments, because it got too messy for me. Moodle uses regex to parse out the tags from a comment, and so I actually used the same (kludgey) logic to assure compatibility. It's really cowboy hacking in PEGjs because you have to save the info (but also take care to unsave it whenever a comment that is matched in the parse turns out NOT to be the full part of the thing you're parsing). 

I had argued in the Moodle forum to use `@`  or something (instead of overloading comments, which should not be part of a question's metadata). Unfortunately, I was too late and even if I had been on time, their culture is not one of formal things such as grammars or XML that is "schema-able". It's a great example in my course of technical debt due to early design choices that aren't fixed. It would be a piece of cake to parse tags a question like:

```
@@tag1, tag2,another tag with a comma (\,) embedded@@::Description::Essay question {}
```

**Comment by ethan-ou** [comment]
We don't place enough emphasis on all the cultural and social factors that shape technical decisions :cry:

When tsd starts working again you'll likely want to update the package. It'll probably be somewhere at `0.16.0` and above when it implements that change. I'll let you know when that happens.

In the meantime, I booted up a codesandbox with the package and it looks like everything's working!

chrome_Rdj7Il0Sl2

**Pull request merged**
